services:
  service1:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - mode: ingress
        target: 8080
        published: 8080
    environment:
      - COHERE_API_KEY=${nHY40cmLrHrcUFPalGzIxG7oikQkDl19g9SBRi6r}
      - PORT=8080
